[package]
name = "ddns-route53"
description = "DDNS client for (AWS) Route53"
keywords = ["DDNS", "Route53"]
version = "0.1.0"
edition = "2021"
authors = ["john@jnelson.ca"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
derivative = "2.2.0"
netdev = "0.30.0"
igd-next = "0.14.3"
log = "0.4.22"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
simple_logger = "5.0.0"
tokio = { version = "1", features = ["macros","rt"] }
toml = "0.8.14"

[profile.release]
#strip = true  # Strip symbols from resulting binary
lto = true  # Enable link-time optimizations
codegen-units = 1  # Having >1 code-gen unit disables some possible optimizations
